---
sidebar: sidebar 
permalink: alerts-faq.html 
keywords: alerts faq, alerts frequently asked questions, bluexp, bluexp alert 
summary: 如果您只是在寻找问题的快速答案、此BlueXP  警报常见问题解答可以为您提供帮助。 
---
= BlueXP  警报的常见问题
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
如果您只是想快速了解问题解答，此常见问题解答会很有帮助。



== 访问BlueXP  警报

*什么是BlueXP  警报URL？*对于URL、在浏览器中输入： https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/"^] 以访问BlueXP  控制台。

*使用BlueXP  警报是否需要许可证？*

BlueXP  警报服务需要NetApp ONTAP 9 10或更高版本的许可证。无需在BlueXP  电子钱包中输入许可证。

您不需要拥有此服务的试用许可证。

*如何启用BlueXP  警报？*BlueXP  警报不需要任何启用。BlueXP  左侧导航栏会自动启用警报选项。

要开始使用、在使用BlueXP  连接器时、它将包括适用于此服务的功能。

** BlueXP  警报是否可在标准模式、受限模式和私用模式下使用？**此服务只能按BlueXP  标准(公共)进行部署。

有关所有BlueXP  服务中这些模式的说明，请参阅 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXP部署模式"^]。

**如何处理访问权限？**只有BlueXP  组织管理员才能启动BlueXP  警报服务并发现工作负载(因为这涉及到对资源的使用)。

根据已登录用户对该BlueXP  组织中集群资源的访问权限、系统会向其显示警报。

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-netapp-accounts.html["了解BlueXP  组织"](英文)



== 查看警报

**我需要等待多长时间才能收到警报？**

首次发现时最多等待15分钟、之后最多等待5分钟、以便显示警报。这因警报而异。

**如果没有BlueXP  Connecter*，为什么在使用直接模式时看不到ONTAP的警报

BlueXP  警报只能使用内部标准BlueXP  连接器。使用直接模式不会监控集群、也不会显示警报。

**为什么有些警报从"警报"列表页面中消失？**

警报功能可将某些警报保持为"活动"状态、并在满足计数器条件或达到时间段后关闭它们。这因警报而异。

要查看所有警报、请选择状态列筛选器、然后选择关闭选项。



== 显示信息

**哪种设备分辨率是最佳的？**BlueXP  警报的建议设备分辨率为"12X1080/"或更高。

**我应该使用哪种浏览器？**任何现代浏览器都能正常工作。
