---
sidebar: sidebar 
permalink: concept-alerts.html 
keywords: netapp, ontap, alert, capacity, performance, availability, security, protection, bluexp, bluexp alerts 
summary: BlueXP  警报是一项服务、可用于查看NetApp ONTAP环境中与容量、性能、可用性和安全性相关的问题或潜在风险。借助此服务、您可以使用ONTAP系统管理器深入了解详细信息。 
---
= 了解BlueXP  警报
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  警报是一项服务、通过该服务、您可以使用标准BlueXP  连接器查看NetApp内部ONTAP环境中的问题或潜在风险。借助此服务、您可以使用ONTAP系统管理器深入了解详细信息。



== 您可以对BlueXP  警报执行哪些操作

BlueXP  警报服务可帮助您随时了解ONTAP存储环境中的风险或潜在风险。此服务会向您显示一些非EMS警报和一些EMS警报。BlueXP  警报服务可提供有关以下严重程度和影响方面的信息：

* *严重性*：严重、警告、信息性
* *影响区域*：容量、性能、保护、可用性、安全性、配置



TIP: BlueXP  UI右上角的通知选项可监控BlueXP  正在执行的操作状态、以帮助您确定需要解决的问题。您可以将这些通知发送到您的电子邮件中。通知选项不包括来自BlueXP  警报服务的警报。



== 使用BlueXP  警报的优势

BlueXP  警报具有以下优势：

* 跨集群获取有关ONTAP存储的警报。
* 在用于其他服务的同一BlueXP  UI中查看警报。
* 深入了解ONTAP集群上的警报—从BlueXP  警报开始、然后在ONTAP系统管理器中查看详细信息。




== 成本

完整版本的BlueXP  警报可与NetApp ONTAP许可证结合使用。



== 许可

BlueXP  警报服务需要NetApp ONTAP 9 10或更高版本的许可证。

您不需要拥有此服务的试用许可证。

此服务只能在BlueXP  标准(公共)模式下部署。



== BlueXP  警报的工作原理

BlueXP  警报服务是BlueXP  的核心组件。BlueXP  警报服务可监控ONTAP集群并从ONTAP接收警报数据。

BlueXP  警报仅在BlueXP  SaaS环境中可用。在本地连接器UI中不可用。



== 支持的工作环境和数据源

使用BlueXP  警报检查以下工作环境和数据源中的问题。

*支持的工作环境*

支持内部ONTAP NAS或SAN工作环境。

目前不支持Cloud Volumes ONTAP工作环境。

*支持的数据源*

此服务可提供有关ONTAP中发生的某些事件的警报。它们是EMS和基于指标的警报的组合。
